### ISSUE TITLE
Code blocks in-between lists causes issues and merging of lines

### ISSUE THREAD

**Issue by NessDan** [nocd5/md2html#11]
When writing the markdown shown here, the resulting md2html output looks like this:

``````md
## Adding SMTP Email support

1. Add the following line to your `build.gradle` file:

    ```kotlin
    implementation("REDACTED")
    ```

   * Please make sure to replace the version with the latest non-snapshot version of core.

1. In your `application.yml` file add the following properties:

    ```yaml
    smtp:
      host: localhost
      port: 25 # Optional (default 25)
      username: myusername # Optional
      password: mypassword # Optional
    ```
``````

![image](https://user-images.githubusercontent.com/304269/195433862-52f0cc88-89cc-41c5-a155-6733d80b7cbd.png)

![image](https://user-images.githubusercontent.com/304269/195433940-43cae473-7203-4729-99fe-f338751f499b.png)
